# Generated by Django 5.1.1 on 2024-09-22 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=256)),
                ('description', models.TextField(max_length=2048)),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=5)),
                ('image', models.ImageField(blank=True, null=True, upload_to='posts/')),
                ('address', models.CharField(max_length=512)),
                ('pincode', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=64)),
                ('estimated_delivery_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
